name: 'Setup Dependencies'
description: 'A custom GitHub Action to set up project dependencies.'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '16'
  install-command:
    description: 'Command to install dependencies'
    required: false
    default: 'npm install'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'blue'